name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5 \
            libncurses5-dev \
            libffi-dev \
            libssl-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.37
          pip install buildozer
          pip install virtualenv

      - name: Accept Android licenses
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Prepare Buildozer
        run: |
          buildozer --version

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fc27-unofficial-apk
          path: bin/*.apk
